#
# This file is part of Web Land Trajectory Service.
# Copyright (C) 2020-2021 INPE.
#
# Web Land Trajectory Service is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

kind: pipeline
name: wlts

steps:
- name: build
  image: python:3.7
  environment:
    WLTS_TEST_ACCESS_TOKEN: cRX9fYsT8rQiYXMaPdmUsMwV9McPfnsUJb65aBucTv
    BDC_AUTH_CLIENT_ID: _xwbynWdVGBt-X8DbBYoC6sGw5MmQwD5
    BDC_AUTH_CLIENT_SECRET: GOC6-7NSTzCUbUm9NO3_gUpqGTJp0kNpt5hQHMnNNONs-5SnSVp1lLZembicQbMD
    BDC_AUTH_ACCESS_TOKEN_URL: https://brazildatacube.dpi.inpe.br/auth/v1/oauth/introspect
  commands:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -e .[tests,docs]
  - ./run-tests.sh

- name: coverage
  image: plugins/codecov
  settings:
    files:
    - coverage.xml
    - .coverage
    token:
      from_secret: codecov_token
  when:
    event:
    - push

- name: discord-notify
  image: brazildatacube/bdc-drone-discord
  settings:
    webhook:
      from_secret: discord_webhook
  when:
    status:
      - failure
      - success

- name: docker-registry
  image: plugins/docker
  settings:
    auto_tag: true
    username:
      from_secret: registry_user
    password:
      from_secret: registry_pass
    registry: registry.dpi.inpe.br
    repo: registry.dpi.inpe.br/${DRONE_REPO}
    custom_dns: 150.163.2.4