sudo: false

language: python

dist: trusty

python:
  - "3.5"

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --upgrade wheel

install:
    - pip install -e .[tests]

script:
    - ./run-test.sh