sudo: false

language: python

cache:
    directories:
        - $HOME/.cache/pip

branches:
    only:
        - master
        - b-0.2

dist: bionic

env:
  global:
    - CPLUS_INCLUDE_PATH=/usr/include/gdal
    - C_INCLUDE_PATH=/usr/include/gdal

addons:
  apt:
    packages:
    - libhdf5-serial-dev
    - libgdal-dev
python:
   - "3.7"

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --upgrade wheel
    - pip install GDAL==`gdalinfo --version | cut -d' ' -f2 | cut -d',' -f1`

install:
    - pip install -e .[tests,docs]

script:
    - ./run-tests.sh

after_success:
    - coveralls