sudo: false

language: python

cache:
    directories:
        - $HOME/.cache/pip

branches:
    only:
        - master

dist: bionic

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libgdal-dev

python:
   - "3.7"

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --upgrade wheel

install:
    - pip install numpy
    - pip install GDAL==$(gdal-config --version) --global-option=build_ext --global-option="$(gdal-config --cflags)"
    - pip install -e .[tests,docs]

script:
    - ./run-tests.sh

after_success:
    - coveralls