sudo: false

language: python

cache:
    directories:
        - $HOME/.cache/pip

dist: bionic

python:
   - "3.7"

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --upgrade wheel
    - export C_INCLUDE_PATH="/usr/include/gdal"
    - export CPLUS_INCLUDE_PATH="/usr/include/gdal"
    - pip install "gdal==2.4.2"

install:
    - pip install -e .[tests,docs]

script:
    - ./run-tests.sh

after_success:
    - coveralls