openapi: 3.0.0
info:
  description: >
    Web Land Trajectory Services. You can find out more about WLTS at
    [https://github.com/brazil-data-cube/wlts](https://github.com/brazil-data-cube/wlts)
  version: '1.0'
  title: Web Land Trajectory Services
  contact:
    name: Example
    email: example@example.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'https://localhost/wlts'
    description: Production server
paths:
  /list_collections:
    get:
      summary: List Collections
      description: Retrieve list of available collections
      parameters:
        - in: query
          name: collection_type
          description: >
            Identifier of collection type. i.e `collection_type=image_collection
            or collection_type=feature_collection`
          schema:
            type: string
      responses:
        '200':
          description: Array of collections
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionList'
  /trajectory:
    get:
      summary: Trajectory
      description: >
        Retrieves the trajectories of collections associated with a given
        location in space. The property `result` contains the feature identifier
        information, class, time, geometry, and the belonging collection.
      parameters:
        - in: query
          name: collections
          description: >-
            List of collections name delimited by comma. i.e
            `collections=prodes,deter`
          required: false
          schema:
            type: string
        - in: query
          name: latitude
          description: Latitude coordinate. i.e `latitude=−6.99`
          required: true
          schema:
            type: number
        - in: query
          name: longitude
          description: Longitude coordinate. i.e `longitude=−50.9498`
          required: true
          schema:
            type: number
        - in: query
          name: start_date
          required: false
          description: Start date. i.e `start_date=2007-01-01`
          schema:
            type: string
        - in: query
          name: end_date
          required: false
          description: End date. i.e `end_date=2017-12-31`
          schema:
            type: string
        - in: query
          name: class_type
          required: false
          description: Class type `class_type=original` or `class_type=map`
          schema:
            type: string

      responses:
        '200':
          description: Trajectory found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trajectory'
        '400':
          description: Missing required arguments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '404':
          description: Collections not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
  /describe_collection:
    get:
      summary: Describe Collection
      description: Retrieves collection description
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Collection found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionDescription'

  /list_classification_sytem:
    get:
      summary: List Classification System
      description: Retrieve list of available classification system
      responses:
        '200':
          description: Array of classification system
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassificationSystemList'

  /describe_classification_sytem:
    get:
      summary: Describe Classification System
      description: Retrieves all class of classification system
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Classification System found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassificationDescription'

components:
  schemas:
    CollectionList:
      type: object
      properties:
        feature_collection:
          type: array
          items:
            type: string
        image_collection:
          type: array
          items:
            type: string
    Trajectory:
      type: object
      properties:
        result:
          type: object
          properties:
            trajectory:
              type: array
              items:
                type: object
                properties:
                  collection_name:
                    type: string
                  classification_class:
                    type: string
                  data:
                    type: string
                  geom:
                    type: string

        query:
          type: object
          properties:
            collenctions:
              type: array
              items:
                type: string
            longitude:
              type: number
            latitude:
              type: number
            start_date:
              type: string
            end_date:
              type: string
    CollectionDescription:
        type: object
        required:
          - collection_name
        properties:
          name:
            type: string
          description:
            type: string
          collection_type:
            type: string
          resolution_unit:
            type: object
            properties:
              unit:
                type: string
              value:
                type: number
          period:
           type: object
           properties:
              start_date:
                type: string
              end_date:
                type: string
          spatial_extent:
            $ref: '#/components/schemas/SpatialExtent'
          classification_system_class:
            $ref: '#/components/schemas/ClassificationSystemClass'

    ClassificationSystemList:
      type: object
      properties:
        classyfication_system:
          type: array
          items:
            type: string
    ClassificationDescription:
      type: object
      required:
        - classification_system_name
      properties:
        classification_system:
          type: string
        description:
          type: string
        detail:
          type: string
        classification_system_class:
          type: array
          items:
            type: string
    ClassificationSystemClass:
      type: object
      properties:
        classification_system:
          type: string
        description:
          type: string
        class_name:
          type: array
          items:
            type: string
    APIError:
      type: object
      description: Used to describe the error occurred on Request operation
      properties:
        code:
          type: integer
        message:
          type: string
    SpatialExtent:
        type: object
        properties:
          xmin:
            type: number
          xmax:
            type: number
          ymin:
            type: number
          ymax:
            type: number
